import { Card } from "../ui/card"

function MonthlyRecap({ timeStats, topTracks, topArtists, topGenres }) {
	const currentMonth = new Date().toLocaleString("default", { month: "long" })

	return (
		<Card className="bg-gradient-to-br from-black to-purple-900 text-white w-[320px] mx-auto">
			<div className="p-4 flex flex-col gap-3">
				{/* Header */}
				<div className="text-center">
					<h2 className="text-xl font-bold">{currentMonth} Recap</h2>
					<p className="text-xs opacity-75">My Spotify Statistics</p>
				</div>

				{/* Top Track Section */}
				<div className="space-y-2">
					<h3 className="text-sm opacity-75">Top Track</h3>
					<div className="flex items-center gap-3 p-2 bg-white/10 rounded-lg">
						<img
							src={topTracks?.[0]?.album?.images?.[0]?.url}
							alt={topTracks?.[0]?.name}
							className="w-14 h-14 shrink-0 rounded-lg shadow-lg"
						/>
						<div className="flex-1 min-w-0">
							<p className="font-bold text-sm line-clamp-2">
								{topTracks?.[0]?.name}
							</p>
							<p className="text-xs opacity-75 truncate">
								{topTracks?.[0]?.artists?.[0]?.name}
							</p>
						</div>
					</div>
				</div>

				{/* Top Artists Section */}
				<div className="space-y-2">
					<h3 className="text-sm opacity-75">Top Artists This Month</h3>
					<div className="space-y-2">
						{topArtists?.slice(0, 3).map((artist, index) => (
							<div
								key={artist.id}
								className="flex items-center gap-3 p-2 bg-white/10 rounded-lg"
							>
								<img
									src={artist?.images?.[0]?.url}
									alt={artist?.name}
									className="w-10 h-10 rounded-full shadow-lg"
								/>
								<div className="flex items-center h-full min-w-0">
									<p className="text-sm truncate">
										#{index + 1} {artist?.name}
									</p>
								</div>
							</div>
						))}
					</div>
				</div>

				{/* Stats Grid */}
				<div className="grid grid-cols-2 gap-2">
					<div className="p-2 bg-white/10 rounded-lg">
						<h3 className="text-xs opacity-75">Minutes</h3>
						<p className="text-lg">{timeStats?.totalMinutes || 0}</p>
					</div>
					<div className="p-2 bg-white/10 rounded-lg">
						<h3 className="text-xs opacity-75">Top Genre</h3>
						<p className="text-sm">{topGenres?.[0] || "No data"}</p>
					</div>
				</div>

				{/* Footer */}
				<div className="text-center text-xs opacity-75 pt-2 border-t border-white/20">
					Generated by SpotiVerse
				</div>
			</div>
		</Card>
	)
}

export default MonthlyRecap
